// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_sqlite.djinni

#include "NativeMyClientInterface.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeMyClientInterface::NativeMyClientInterface() : ::djinni::JniInterface<::djinni_sqlite::MyClientInterface, NativeMyClientInterface>() {}

NativeMyClientInterface::~NativeMyClientInterface() = default;

NativeMyClientInterface::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeMyClientInterface::JavaProxy::~JavaProxy() = default;

bool NativeMyClientInterface::JavaProxy::log_string(const std::string & c_str) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeMyClientInterface>::get();
    auto jret = jniEnv->CallBooleanMethod(Handle::get().get(), data.method_logString,
                                          ::djinni::get(::djinni::String::fromCpp(jniEnv, c_str)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::Bool::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
