// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_sqlite.djinni

package dyno.fun.djinni_sqlite;

public abstract class MyClientInterface {
    public abstract boolean logString(String str);
}
