// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_sqlite.djinni

#import <Foundation/Foundation.h>


@protocol DSMyClientInterface

- (BOOL)logString:(nonnull NSString *)str;

@end
