// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_sqlite.djinni

#import "DSTodo.h"


@implementation DSTodo

- (nonnull instancetype)initWithId:(int32_t)id
                             label:(nonnull NSString *)label
                         completed:(int32_t)completed
{
    if (self = [super init]) {
        _id = id;
        _label = [label copy];
        _completed = completed;
    }
    return self;
}

+ (nonnull instancetype)todoWithId:(int32_t)id
                             label:(nonnull NSString *)label
                         completed:(int32_t)completed
{
    return [[self alloc] initWithId:id
                              label:label
                          completed:completed];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ label:%@ completed:%@>", self.class, (void *)self, @(self.id), self.label, @(self.completed)];
}

@end
