// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_sqlite.djinni

#import "DSTodo.h"
#import <Foundation/Foundation.h>
@class DSTodoList;
@protocol DSMyClientInterface;


@interface DSTodoList : NSObject

+ (nullable DSTodoList *)createWithPath:(nonnull NSString *)path;

+ (void)setLogger:(nullable id<DSMyClientInterface>)logger;

- (nonnull NSArray<DSTodo *> *)getTodos;

- (int32_t)addTodo:(nonnull NSString *)label;

- (BOOL)updateTodoCompleted:(int32_t)id
                  completed:(int32_t)completed;

- (BOOL)deleteTodo:(int32_t)id;

@end
