// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_sqlite.djinni

#import "DSTodoList+Private.h"
#import "DSTodoList.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "DSMyClientInterface+Private.h"
#import "DSTodo+Private.h"
#import "DSTodoList+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DSTodoList ()

- (id)initWithCpp:(const std::shared_ptr<::djinni_sqlite::TodoList>&)cppRef;

@end

@implementation DSTodoList {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::djinni_sqlite::TodoList>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::djinni_sqlite::TodoList>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable DSTodoList *)createWithPath:(nonnull NSString *)path {
    try {
        auto r = ::djinni_sqlite::TodoList::create_with_path(::djinni::String::toCpp(path));
        return ::djinni_generated::TodoList::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (void)setLogger:(nullable id<DSMyClientInterface>)logger {
    try {
        ::djinni_sqlite::TodoList::set_logger(::djinni_generated::MyClientInterface::toCpp(logger));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<DSTodo *> *)getTodos {
    try {
        auto r = _cppRefHandle.get()->get_todos();
        return ::djinni::List<::djinni_generated::Todo>::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (int32_t)addTodo:(nonnull NSString *)label {
    try {
        auto r = _cppRefHandle.get()->add_todo(::djinni::String::toCpp(label));
        return ::djinni::I32::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)updateTodoCompleted:(int32_t)id
                  completed:(int32_t)completed {
    try {
        auto r = _cppRefHandle.get()->update_todo_completed(::djinni::I32::toCpp(id),
                                                            ::djinni::I32::toCpp(completed));
        return ::djinni::Bool::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)deleteTodo:(int32_t)id {
    try {
        auto r = _cppRefHandle.get()->delete_todo(::djinni::I32::toCpp(id));
        return ::djinni::Bool::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto TodoList::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto TodoList::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DSTodoList>(cpp);
}

}  // namespace djinni_generated

@end
