// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_sqlite.djinni

#import "DSTodo.h"
#include "todo.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DSTodo;

namespace djinni_generated {

struct Todo
{
    using CppType = ::djinni_sqlite::Todo;
    using ObjcType = DSTodo*;

    using Boxed = Todo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
