// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_sqlite.djinni

#include "todo_list.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DSTodoList;

namespace djinni_generated {

class TodoList
{
public:
    using CppType = std::shared_ptr<::djinni_sqlite::TodoList>;
    using CppOptType = std::shared_ptr<::djinni_sqlite::TodoList>;
    using ObjcType = DSTodoList*;

    using Boxed = TodoList;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

