// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_sqlite.djinni

#pragma once

#include <string>

namespace djinni_sqlite {

class MyClientInterface {
public:
    virtual ~MyClientInterface() {}

    virtual bool log_string(const std::string & str) = 0;
};

}  // namespace djinni_sqlite
