// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_sqlite.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace djinni_sqlite {

class MyClientInterface;
struct Todo;

class TodoList {
public:
    virtual ~TodoList() {}

    static std::shared_ptr<TodoList> create_with_path(const std::string & path);

    static void set_logger(const std::shared_ptr<MyClientInterface> & logger);

    virtual std::vector<Todo> get_todos() = 0;

    virtual int32_t add_todo(const std::string & label) = 0;

    virtual bool update_todo_completed(int32_t id, int32_t completed) = 0;

    virtual bool delete_todo(int32_t id) = 0;
};

}  // namespace djinni_sqlite
