// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_sqlite.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace djinni_sqlite {

struct Todo final {
    int32_t id;
    std::string label;
    int32_t completed;

    Todo(int32_t id_,
         std::string label_,
         int32_t completed_)
    : id(std::move(id_))
    , label(std::move(label_))
    , completed(std::move(completed_))
    {}
};

}  // namespace djinni_sqlite
